(function () {
  'use strict';
  const storage = window.CodePlayStorage; const host = document.querySelector('#maze-game'); if (!host) return;
  const levels = [{ id: 'maze-1', name: 'First steps', start: [0, 0, 1], finish: [0, 3], walls: [[1, 1], [2, 3]], size: 5, solution: ['forward', 'forward', 'forward'] }, { id: 'maze-2', name: 'Make a turn', start: [0, 0, 1], finish: [2, 2], walls: [[1, 1], [3, 2]], size: 5, solution: ['forward', 'forward', 'right', 'forward', 'forward'] }, { id: 'maze-3', name: 'Plan ahead', start: [4, 0, 0], finish: [2, 3], walls: [[3, 1], [1, 2], [3, 3]], size: 5, solution: ['forward', 'forward', 'right', 'forward', 'forward', 'forward'] }];
  let level = 0; let commands = []; let robot; let running = false;
  const names = { forward: 'MOVE FORWARD', left: 'TURN LEFT', right: 'TURN RIGHT' }; const arrows = ['&#9650;', '&#9654;', '&#9660;', '&#9664;'];
  const levelSelect = document.querySelector('[data-maze-level]'); levels.forEach((item, index) => { levelSelect.add(new Option(`Level ${index + 1}: ${item.name}`, index)); });
  function updateLevelOptions() { const completedLevels = storage.getProgress().maze.completedLevels; Array.from(levelSelect.options).forEach((option, index) => { option.disabled = index > 0 && !completedLevels.includes(levels[index - 1].id); }); if (levelSelect.options[level].disabled) { level = 0; levelSelect.value = '0'; } }
  function reset() { const current = levels[level]; robot = { row: current.start[0], column: current.start[1], direction: current.start[2] }; commands = []; running = false; draw(); document.querySelector('[data-maze-feedback]').textContent = ''; document.querySelector('[data-maze-status]').textContent = storage.getProgress().maze.completedLevels.includes(current.id) ? 'Level complete' : 'Build your code'; }
  function draw() { const current = levels[level]; const cells = []; for (let row = 0; row < current.size; row += 1) for (let column = 0; column < current.size; column += 1) { const wall = current.walls.some((item) => item[0] === row && item[1] === column); const finish = current.finish[0] === row && current.finish[1] === column; const here = robot.row === row && robot.column === column; cells.push(`<div class="maze-cell${wall ? ' maze-wall' : ''}${finish ? ' maze-finish' : ''}" role="gridcell">${here ? `<span class="robot" aria-label="Robot">${arrows[robot.direction]}</span>` : finish ? '<span aria-label="Finish">&#9733;</span>' : ''}</div>`); } document.querySelector('[data-maze-grid]').innerHTML = cells.join(''); document.querySelector('[data-command-list]').innerHTML = commands.length ? commands.map((command, index) => `<div class="command-chip"><span>${index + 1}</span>${names[command]}</div>`).join('') : '<p class="empty-commands">Your commands will appear here.</p>'; }
  function move(command) { if (command === 'left') robot.direction = (robot.direction + 3) % 4; if (command === 'right') robot.direction = (robot.direction + 1) % 4; if (command === 'forward') { const rows = [-1, 0, 1, 0]; const columns = [0, 1, 0, -1]; robot.row += rows[robot.direction]; robot.column += columns[robot.direction]; } }
  function blocked() { const current = levels[level]; return robot.row < 0 || robot.column < 0 || robot.row >= current.size || robot.column >= current.size || current.walls.some((item) => item[0] === robot.row && item[1] === robot.column); }
  async function run() { if (running || !commands.length) { if (!commands.length) document.querySelector('[data-maze-feedback]').textContent = 'Add at least one command before running.'; return; } running = true; const feedback = document.querySelector('[data-maze-feedback]'); for (const command of commands) { move(command); draw(); await new Promise((resolve) => window.setTimeout(resolve, 280)); if (blocked()) { feedback.textContent = 'Your code needs debugging. The robot hit a wall or left the grid.'; document.querySelector('[data-maze-status]').textContent = 'Try again'; running = false; return; } if (robot.row === levels[level].finish[0] && robot.column === levels[level].finish[1]) { storage.completeMazeLevel(levels[level].id, 20); updateLevelOptions(); feedback.textContent = 'Congratulations! You programmed the robot! +20 points earned.'; document.querySelector('[data-maze-status]').textContent = 'Level complete'; running = false; return; } } feedback.textContent = 'The robot is safe, but it has not reached the finish. Add commands and try again.'; document.querySelector('[data-maze-status]').textContent = 'Keep planning'; running = false; }
  host.addEventListener('click', (event) => { const command = event.target.closest('[data-command]'); if (command && !running) { commands.push(command.dataset.command); draw(); } if (event.target.closest('[data-run-maze]')) run(); if (event.target.closest('[data-clear-maze]') && !running) { commands = []; draw(); } if (event.target.closest('[data-reset-maze]') && !running) reset(); }); levelSelect.addEventListener('change', () => { if (!running && !levelSelect.options[levelSelect.selectedIndex].disabled) { level = Number(levelSelect.value); reset(); } }); updateLevelOptions(); reset();
}());