(function () {
  'use strict';
  const host = document.querySelector('[data-quiz-content]'); if (!host) return;
  const questions = [
    ['What is coding?', ['A set of instructions for a computer', 'A computer screen', 'A type of battery'], 0], ['What does sequence mean?', ['A random collection of ideas', 'Instructions in an order', 'A computer game'], 1], ['What is an algorithm?', ['A step-by-step plan', 'A keyboard key', 'A screen colour'], 0], ['What can a variable store?', ['Only a picture', 'Information such as a score', 'Only a sound'], 1], ['What does IF/ELSE help a program do?', ['Make a choice', 'Turn off every computer', 'Delete instructions'], 0], ['What is a loop useful for?', ['Repeating instructions', 'Renaming a computer', 'Drawing a keyboard'], 0], ['What is a function?', ['A reusable group of instructions', 'A broken program', 'A computer cable'], 0], ['What is a bug?', ['A useful variable', 'A mistake in a program', 'A type of loop'], 1], ['What is debugging?', ['Finding and fixing a mistake', 'Adding random steps', 'Closing a program'], 0], ['What is a good way to solve a big problem?', ['Ignore it', 'Break it into smaller parts', 'Make it more confusing'], 1]
  ]; let index = 0; let score = 0; let locked = false;
  function draw() { const item = questions[index]; document.querySelector('[data-quiz-number]').textContent = `Question ${index + 1} of ${questions.length}`; document.querySelector('[data-quiz-progress]').style.width = `${((index + 1) / questions.length) * 100}%`; host.innerHTML = `<p class="section-kicker">Question ${index + 1}</p><h2>${item[0]}</h2><div class="quiz-options">${item[1].map((answer, answerIndex) => `<label class="quiz-option"><input type="radio" name="quiz-answer" value="${answerIndex}"><span>${answer}</span></label>`).join('')}</div><button class="button button-primary" type="button" data-submit-answer>Check answer</button>`; locked = false; }
  host.addEventListener('click', (event) => { const button = event.target.closest('[data-submit-answer]'); if (!button || locked) return; const selected = host.querySelector('input:checked'); const feedback = document.querySelector('[data-quiz-feedback]'); if (!selected) { feedback.textContent = 'Choose an answer first.'; return; } locked = true; if (Number(selected.value) === questions[index][2]) { score += 1; feedback.textContent = 'Correct!'; } else feedback.textContent = `Not quite. The answer is: ${questions[index][1][questions[index][2]]}.`; button.textContent = index === questions.length - 1 ? 'See my result' : 'Next question'; button.dataset.next = 'true'; event.answerChecked = true; });
  host.addEventListener('click', (event) => { if (event.answerChecked) return; const button = event.target.closest('[data-next]'); if (!button) return; if (index === questions.length - 1) { window.CodePlayStorage.saveQuizResult(score, questions.length); document.querySelector('[data-quiz-number]').textContent = 'Quiz complete'; document.querySelector('[data-quiz-progress]').style.width = '100%'; host.innerHTML = `<p class="section-kicker">Your result</p><h2>${score} / ${questions.length} correct</h2><p class="result-copy">That is ${score * 10}% of the questions. Keep practising and try again to improve your understanding.</p><button class="button button-primary" type="button" data-retry-quiz>Try again</button>`; document.querySelector('[data-quiz-feedback]').textContent = `Quiz complete. You earned up to 30 points on your first completed attempt.`; return; } index += 1; document.querySelector('[data-quiz-feedback]').textContent = ''; draw(); });
  host.addEventListener('click', (event) => { if (event.target.closest('[data-retry-quiz]')) { index = 0; score = 0; document.querySelector('[data-quiz-feedback]').textContent = ''; draw(); } }); draw();
}());